import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import { useAccount } from "wagmi";

import spindl from "@spindl-xyz/attribution";
// import spindl from "@spindl-xyz/attribution-lite"; // for lite version customers

const Home: NextPage = () => {
  const { address } = useAccount();

  useEffect(() => {
    if (address) {
      spindl.attribute(address);
    }
  }, [address]);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <br />

        <button
          onClick={() => {
            spindl.track(
              "test_event",
              {
                custom: "data goes here",
              },
              {
                address: "0x1234...", // optional
                customerUserId: "1234", // optional
              }
            );
          }}
        >
          Track Custom Event
        </button>

        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{" "}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
};

export default Home;
